# Generated by Django 4.0.6 on 2022-07-27 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wxUser',
            fields=[
                ('openid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('session_key', models.CharField(max_length=64)),
                ('nickname', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=64)),
                ('avatar', models.CharField(max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('create_ip', models.CharField(max_length=64)),
                ('token', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='wxUserLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=64)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('create_ip', models.CharField(max_length=64)),
                ('action', models.CharField(max_length=64)),
                ('action_detail', models.CharField(max_length=64)),
            ],
        ),
    ]
